name = "vaccination-app"
main = "worker.js"
compatibility_date = "2025-10-16"

[[d1_databases]]
binding = "DB"
database_name = "vaccination_db_v2"
database_id = "c51b4103-a5a9-45c7-b601-68731397ec1c"
